### ISSUE TITLE
Unknow error "thread 'main' panicked at celeste/src/launch.rs:1920:33:"

### ISSUE THREAD

**Issue by vvitorveloso** [hwittenborn/celeste#145]
Celeste close some seconds after i open it:

```
thread 'main' panicked at celeste/src/launch.rs:1920:33:
internal error: entered unreachable code
stack backtrace:
```

Terminal doesn't show anything more, i don't know if i using the RUST_BACKTRACE correctly 

```
130 ochi@OCHINOTE ~ % RUST_BACKTRACE=full celeste

(process:10459): Gtk-WARNING **: 07:47:33.858: Unknown key gtk-modules in /home/ochi/.config/gtk-4.0/settings.ini

(process:10474): Gtk-WARNING **: 07:47:33.941: Unknown key gtk-modules in /home/ochi/.config/gtk-4.0/settings.ini

(celeste:10474): Adwaita-CRITICAL **: 07:47:34.026: ../libadwaita/src/adw-header-bar.c:917: tried to remove non-child 0x561726573870 of type 'GtkButton' from 0x56172648be50 of type 'AdwHeaderBar'

(celeste:10474): Adwaita-CRITICAL **: 07:47:34.026: ../libadwaita/src/adw-header-bar.c:917: tried to remove non-child 0x56172657e810 of type 'GtkButton' from 0x56172657ae50 of type 'AdwHeaderBar'
Info: Starting up tray binary...
thread 'main' panicked at celeste/src/launch.rs:1920:33:
internal error: entered unreachable code
stack backtrace:
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

**Comment by hwittenborn** [comment]
Is there any chance you're syncing to Google Drive? That's been a common culprit for causing that error (though I'm not positive on the cause yet).

**Comment by vvitorveloso** [comment]
Yes, it's with Google drive account

**Comment by nort4n** [comment]
same error using celeste for syncing my google drive on pop os

**Comment by rowanfr** [comment]
If I had to guess it's likely something to do with `unreachable!();` here:

https://github.com/hwittenborn/celeste/blob/develop/src/launch.rs#L2488-L2490

The error that I'm getting is:
```
thread 'main' panicked at src/launch.rs:2406:33: 
internal error: entered unreachable code stack 
backtrace:
```
