### ISSUE TITLE
Installed celeste as snap in WSL2, crashed on startup

### ISSUE THREAD

**Issue by schliemannosaurusrex** [hwittenborn/celeste#151]
I ran the following commands after fresh WSL Ubuntu installation:

$ sudo snap install celeste
$ celeste

got a window titled "Unknown error - Celeste":

thread 'main' panicked at celeste/src/launch.rs:251:38:
called `Result::unwrap()` on an `Err` value: InputOutput(Os { code: 2, kind: NotFound, message: "No such file or directory" })
stack backtrace:
   0: rust_begin_unwind
             at /rustc/960754090acc9cdd2a5a57586f244c0fc712d26c/library/std/src/panicking.rs:597:5
   1: core::panicking::panic_fmt
             at /rustc/960754090acc9cdd2a5a57586f244c0fc712d26c/library/core/src/panicking.rs:72:14
   2: core::result::unwrap_failed
             at /rustc/960754090acc9cdd2a5a57586f244c0fc712d26c/library/core/src/result.rs:1653:5
   3: celeste::launch::launch
   4: <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline
   5: g_closure_invoke
   6: <unknown>
   7: <unknown>
   8: g_signal_emit_valist
   9: g_signal_emit
  10: <unknown>
  11: g_application_run
  12: <O as gio::application::ApplicationExtManual>::run_with_args
  13: celeste::main

**Comment by hwittenborn** [comment]
Thanks for the issue @schliemannosaurusrex! The parts of the codebase involved with that error were recently removed - could you try updating the snap and see if anything changes?

**Comment by schliemannosaurusrex** [comment]
Hi, WSL="pain in the ass". I reinstalled and tried with the updated snap and no errors. It Just didn't work anyway because of $WSL. I guess the corporate proxy settings seem to interfere the connection. I Just hatte Windows. Thanks anyway.
