### ISSUE TITLE
"this is an internal issue with celeste and should be reported"

### ISSUE THREAD

**Issue by donbright** [hwittenborn/celeste#176]
thread 'main' panicked at src/launch.rs:2406:33:
internal error: entered unreachable code
stack backtrace:

(yes the backtrace was literally blank)

**Comment by hwittenborn** [comment]
Hey @donbright, I'm pretty sure the lack of a backtrace is due to some internal logic for how Celeste captures backtraces (I'm not positive, but you're not the first person to have a blank backtrace).

Would there be any chance you're using Google Drive to sync your files? That's where I've been seeing this issue in the past.

**Comment by vcarel** [comment]
Hi, I just tried to sync Google Drive from scratch and I got the same error. Empty stacktrace too.

**Comment by johnblommers** [comment]
I just installed Celeste and setup Google Drive, pCloud and Dropbox. After a while, I also get this unknown error, though in a different place:

```
thread 'main' panicked at src/launch.rs:2020:54:
called `Option::unwrap()` on a `None` value
stack backtrace:

no backtrace.

**Comment by yy00ch** [comment]
Just reporting that I've encountered a similar issue when I tried to sync google drive on pop os.

`thread 'main' panicked at src/launch.rs:2406:33:
internal error: entered unreachable code
stack backtrace:`

**Comment by Gotterbild** [comment]
First, thanks for you work! I know how to use rclone, but having a nice native GUI always feels better.

Just got the same error with Proton, no backtrace:

```
thread 'main' panicked at src/launch.rs:1882:34:
called `Option::unwrap()` on a `None` value
stack backtrace:
```

I was syncing two folders, one of which is ~75MB and 920 files and the other  one is 2MB, 5 files.

I should say the sync process is pretty slow as first folder was checking for more than 10 hours. Maybe more. And I'm not positive if it finished and on which sync step the error happened.

With direct use of rclone the process was way way faster, even with defaults. By default rclone uses 4 threads and it seems Celeste using only one. Would be nice to have ability to set `--multi-thread-streams` as you want per service.

**Comment by donbright** [comment]
@hwittenborn  yup, was using Google Drive from linux mint. Thanks.

**Comment by diogotcorreia** [comment]
Just got this as well. Also Google Drive.
Is there any information I could provide that would help with the issue?

**Comment by diogotcorreia** [comment]
Update: Instead of running with flatpak, I'm now running with the package from Nixpkgs.
It apparently shows the stack trace now, which might by useful:

```
thread 'main' panicked at src/launch.rs:2406:33:
internal error: entered unreachable code
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: celeste::launch::launch::sync_remote_directory
   4: celeste::launch::launch::sync_remote_directory::{{closure}}
   5: celeste::launch::launch::sync_remote_directory
   6: celeste::launch::launch::sync_remote_directory::{{closure}}
   7: celeste::launch::launch::sync_remote_directory
   8: celeste::launch::launch::sync_remote_directory::{{closure}}
   9: celeste::launch::launch::sync_remote_directory
  10: celeste::launch::launch::sync_remote_directory::{{closure}}
  11: celeste::launch::launch::sync_remote_directory
  12: celeste::launch::launch::sync_remote_directory::{{closure}}
  13: celeste::launch::launch::sync_remote_directory
  14: celeste::launch::launch
  15: <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline
  16: g_closure_invoke
  17: signal_emit_unlocked_R.isra.0
  18: signal_emit_valist_unlocked
  19: g_signal_emit_valist
  20: g_signal_emit
  21: g_application_real_local_command_line
  22: g_application_run
  23: <O as gio::application::ApplicationExtManual>::run_with_args
  24: celeste::main
```

**Comment by diogotcorreia** [comment]
I've built Celeste locally and added some `dbg!` prints and found out that this issue is caused by duplicate file names in Google Drive (i.e., GDrive allows you to have two distinct files with the same name).
![image](https://github.com/hwittenborn/celeste/assets/7467891/596003ea-1988-4567-b697-ba0ef3751712)
![image](https://github.com/hwittenborn/celeste/assets/7467891/4bcef100-f63c-4839-a875-226f8def3eb5)

**Comment by hwittenborn** [comment]
Thanks for the information @diogotcorreia! Do you have two files with the same name on your Google Drive in your case then?

**Comment by diogotcorreia** [comment]
@hwittenborn I have indeed 🙃
I've left more information and reproducible steps in #193
