### ISSUE TITLE
Unknown Error

### ISSUE THREAD

**Issue by BBBalls** [hwittenborn/celeste#181]
I saved a ODS file from LibreOffice Calc to my local sync folder for Proton Drive, and both the ODS file and the .~lock file where synced. After closeing the LibreOffice Calc instance, the disappearance of the .~lock file generated an `directory not found` error in Celeste, which I dismissed. The .~lock file remained in Proton Drive. When I deleted the .~lock file from Proton Drive, Celeste crashed with an error notification, which requests a report.

`thread 'main' panicked at src/launch.rs:2435:50:`
`called Option::unwrap() on a None value`
`stack backtrace:`

After restarting Celeste, the .~lock file reapearred in both the local sync folder and in Proton Drive. I deleted the .~lock file from the local folder, and again received an `directory not found` error notice, but I did not dismiss it. I then deleted the .~lock file from Proton Drive, with no apparent ill effect. Then I dismissed the `directory not found` error notice, also will no apparent ill effect.

I have not been able to replicate the initial crash. Now when the .~lock file is removed locally, the `directory not found` error still appears, but after dismissing the error and then deleting the .~lock file in Proton Drive, the sync occurs in an expected manner.

Deleting the .~lock file from Proton Drive first deleted the .~lock file from the local folder in an expected manner.

**Comment by Loppansson** [comment]
I'm getting a very similar looking error using Murena Cloud:

```
thread 'main' panicked at src/launch.rs:1882:34:
called `Option::unwrap()` on a `None` value
stack backtrace:
```

I can however not locate a .~lock file, nor locally nor in Murena Cloud.

**Comment by BBBalls** [comment]
@Loppansson

To see the .~lock file locally you will have to enable seeing hidden files in you file manager, and the document needs to be open in LibreOffice. When the document is closed from LibreOffice the .~lock file is automatically removed. Celeste needs to be open and syncing from the same directory as the open LibreOffiice document. If the LibreOffice document file name is `foo.ods`, the .~lock file will be named `.~lock.foo.ods`.

**Comment by Loppansson** [comment]
Ah, aright! Thank u!
