### ISSUE TITLE
unknown error when syncing wiht google drive

### ISSUE THREAD

**Issue by KlimaRitter** [hwittenborn/celeste#204]
i get this error that i dont understant

```
thread 'main' panicked at src/launch.rs:2406:33:
internal error: entered unreachable code
stack backtrace:
```

**Comment by Nakaura-T** [comment]
me too

**Comment by mervin8or** [comment]
I have the same as well. Recently setup a laptop with Linux Mint 21.3 Cinnamon in order to move away from Windows.
Currently working through alternative apps for those I use on Windows (surprising how many are actually available as Linux apps!) and found Celeste to sync my Google drive.
It worked well to start with but now produces this error every time I run it. Willing to help with some testing if needed ...

**Comment by Grubben** [comment]
im getting this on debian as well!

**Comment by alex-carranza** [comment]
Similar issue, different line number:

thread 'main' panicked at src/launch.rs:1995:33:
internal error: entered unreachable code
stack backtrace:

Running celeste from the command line doesn't yield any further information.
