### ISSUE TITLE
Celeste crashes when syncing Google Drive

### ISSUE THREAD

**Issue by rolandixor** [hwittenborn/celeste#212]
Here's the backtrace:

thread 'main' panicked at src/launch.rs:1884:34:
called `Option::unwrap()` on a `None` value
stack backtrace:
thread 'main' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x5d24b9657905 - <unknown>
   1:     0x5d24b96865eb - <unknown>
   2:     0x5d24b9653ecf - <unknown>
   3:     0x5d24b96576de - <unknown>
   4:     0x5d24b9658c29 - <unknown>
   5:     0x5d24b96589cc - <unknown>
   6:     0x5d24b9659201 - <unknown>
   7:     0x5d24b9659033 - <unknown>
   8:     0x5d24b9657dc9 - <unknown>
   9:     0x5d24b9658d44 - <unknown>
  10:     0x5d24b9683565 - <unknown>
  11:     0x5d24b96835f2 - <unknown>
  12:     0x5d24b9683736 - <unknown>
  13:     0x5d24b7783f04 - <unknown>
  14:     0x767db340c43a - g_closure_invoke
  15:     0x767db342096c - <unknown>
  16:     0x767db34223f1 - <unknown>
  17:     0x767db34283c1 - g_signal_emit_valist
  18:     0x767db3428483 - g_signal_emit
  19:     0x767db26fe9b8 - <unknown>
  20:     0x767db26feb1b - g_application_run
  21:     0x5d24b764cec8 - <unknown>
  22:     0x5d24b76f40e7 - <unknown>
  23:     0x5d24b7827a63 - <unknown>
  24:     0x5d24b7727c79 - <unknown>
  25:     0x5d24b964b782 - <unknown>
  26:     0x5d24b76f7205 - <unknown>
  27:     0x767db233408a - <unknown>
  28:     0x767db233414b - __libc_start_main
  29:     0x5d24b760e025 - <unknown>
  30:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.

**Comment by Jordan-Pyper** [comment]
Same problem here. The application is unusable as is.

**Comment by bukbr** [comment]
Same... crash!!!

thread 'main' panicked at src/launch.rs:1884:34:
called `Option::unwrap()` on a `None` value
stack backtrace:
thread 'main' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x635a938b3905 - <unknown>
   1:     0x635a938e25eb - <unknown>
   2:     0x635a938afecf - <unknown>
   3:     0x635a938b36de - <unknown>
   4:     0x635a938b4c29 - <unknown>
   5:     0x635a938b49cc - <unknown>
   6:     0x635a938b5201 - <unknown>
   7:     0x635a938b5033 - <unknown>
   8:     0x635a938b3dc9 - <unknown>
   9:     0x635a938b4d44 - <unknown>
  10:     0x635a938df565 - <unknown>
  11:     0x635a938df5f2 - <unknown>
  12:     0x635a938df736 - <unknown>
  13:     0x635a919dff04 - <unknown>
  14:     0x73bd727a891a - g_closure_invoke
  15:     0x73bd727bd5c3 - <unknown>
  16:     0x73bd727bf071 - <unknown>
  17:     0x73bd727c4e01 - g_signal_emit_valist
  18:     0x73bd727c4ec3 - g_signal_emit
  19:     0x73bd718fe120 - <unknown>
  20:     0x73bd718fe2d7 - g_application_run
  21:     0x635a918a8ec8 - <unknown>
  22:     0x635a919500e7 - <unknown>
  23:     0x635a91a83a63 - <unknown>
  24:     0x635a91983c79 - <unknown>
  25:     0x635a938a7782 - <unknown>
  26:     0x635a91953205 - <unknown>
  27:     0x73bd713eb188 - <unknown>
  28:     0x73bd713eb24b - __libc_start_main
  29:     0x635a9186a025 - <unknown>
  30:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.

**Comment by juanker-cso** [comment]
Same here. 
Syncing worked for a while
then I found out it hadn't ran in months on 2 devices so I open it
on one device (running mint 22.1 XFCE) it works fine
on the one running Plasma 5.27.12 it tried to sync, and even loaded a folder and a single subfolder, but then crashed
Now it keeps crashing.

OS: Linux Mint 22.1 x86_64 
Kernel: 6.8.0-71-generic 

thread 'main' panicked at src/launch.rs:1884:34:
called `Option::unwrap()` on a `None` value
stack backtrace:
thread 'main' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x627a501d4905 - <unknown>
   1:     0x627a502035eb - <unknown>
   2:     0x627a501d0ecf - <unknown>
   3:     0x627a501d46de - <unknown>
   4:     0x627a501d5c29 - <unknown>
   5:     0x627a501d59cc - <unknown>
   6:     0x627a501d6201 - <unknown>
   7:     0x627a501d6033 - <unknown>
   8:     0x627a501d4dc9 - <unknown>
   9:     0x627a501d5d44 - <unknown>
  10:     0x627a50200565 - <unknown>
  11:     0x627a502005f2 - <unknown>
  12:     0x627a50200736 - <unknown>
  13:     0x627a4e300f04 - <unknown>
  14:     0x7edb6dc3191a - g_closure_invoke
  15:     0x7edb6dc46603 - <unknown>
  16:     0x7edb6dc480b1 - <unknown>
  17:     0x7edb6dc4de41 - g_signal_emit_valist
  18:     0x7edb6dc4df03 - g_signal_emit
  19:     0x7edb6ccfe120 - <unknown>
  20:     0x7edb6ccfe2c3 - g_application_run
  21:     0x627a4e1c9ec8 - <unknown>
  22:     0x627a4e2710e7 - <unknown>
  23:     0x627a4e3a4a63 - <unknown>
  24:     0x627a4e2a4c79 - <unknown>
  25:     0x627a501c8782 - <unknown>
  26:     0x627a4e274205 - <unknown>
  27:     0x7edb6c7eb3c8 - <unknown>
  28:     0x7edb6c7eb48b - __libc_start_main
  29:     0x627a4e18b025 - <unknown>
  30:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
