### ISSUE TITLE
[Bug]: Panic "thread 'main' panicked at src/launch.rs:2040:33"

### ISSUE THREAD

**Issue by IVoyt** [hwittenborn/celeste#218]
### Bug Description

periodically celeste snap package stops working with panic
```
thread 'main' panicked at src/launch.rs:2040:33:
internal error: entered unreachable code
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: celeste::launch::launch::sync_local_directory
   4: celeste::launch::launch
   5: <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline
   6: g_closure_invoke
   7: <unknown>
   8: <unknown>
   9: g_signal_emit_valist
  10: g_signal_emit
  11: <unknown>
  12: g_application_run
  13: <O as gio::application::ApplicationExtManual>::run_with_args
  14: celeste::main
thread 'main' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x56480bb9e905 - <std::sys::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd7fe9da464dc613a
   1:     0x56480bbcd5eb - core::fmt::write::h31992ea73d92ffa4
   2:     0x56480bb9aecf - std::io::Write::write_fmt::h5015b998fbd1cf65
   3:     0x56480bb9e6de - std::sys::backtrace::print::h5f3f79d7ee85f598
   4:     0x56480bb9fc29 - std::panicking::default_hook::{{closure}}::hf313047c6f9a0750
   5:     0x56480bb9f9cc - std::panicking::default_hook::hd96acc715f65b6d7
   6:     0x56480bba0201 - std::panicking::rust_panic_with_hook::hc3b55609717126a2
   7:     0x56480bba0033 - std::panicking::begin_panic_handler::{{closure}}::h6a0db00056d37e77
   8:     0x56480bb9edc9 - std::sys::backtrace::__rust_end_short_backtrace::h8bf20a85e9b83f5c
   9:     0x56480bb9fd44 - rust_begin_unwind
  10:     0x56480bbca565 - core::panicking::panic_nounwind_fmt::hc22db378155c4432
  11:     0x56480bbca5f2 - core::panicking::panic_nounwind::he931df6ed8de2736
  12:     0x56480bbca736 - core::panicking::panic_cannot_unwind::h46449aa9b12c6d31
  13:     0x564809ccaf04 - <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline::hbe8669dd5c700595
  14:     0x7f45e2ccf32f - g_closure_invoke
  15:     0x7f45e2ce52bb - <unknown>
  16:     0x7f45e2ce7f83 - <unknown>
  17:     0x7f45e2cf13f9 - g_signal_emit_valist
  18:     0x7f45e2cf14c3 - g_signal_emit
  19:     0x7f45e200cee8 - <unknown>
  20:     0x7f45e200d066 - g_application_run
  21:     0x564809b93ec8 - <O as gio::application::ApplicationExtManual>::run_with_args::hf3ae39b800c31d15
  22:     0x564809c3b0e7 - celeste::main::h478561235040638f
  23:     0x564809d6ea63 - std::sys::backtrace::__rust_begin_short_backtrace::h4e646722653f7fdc
  24:     0x564809c6ec79 - std::rt::lang_start::{{closure}}::hb1f9c1b6a30502c1
  25:     0x56480bb92782 - std::rt::lang_start_internal::h55c3af6c910a5833
  26:     0x564809c3e205 - main
  27:     0x7f45e1a9ed90 - <unknown>
  28:     0x7f45e1a9ee40 - __libc_start_main
  29:     0x564809b55025 - _start
  30:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
```

```
thread 'main' panicked at src/launch.rs:2040:33:
internal error: entered unreachable code
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: celeste::launch::launch::sync_local_directory
   4: celeste::launch::launch
   5: <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline
   6: g_closure_invoke
   7: <unknown>
   8: <unknown>
   9: g_signal_emit_valist
  10: g_signal_emit
  11: <unknown>
  12: g_application_run
  13: <O as gio::application::ApplicationExtManual>::run_with_args
  14: celeste::main
thread 'main' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x56480bb9e905 - <std::sys::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd7fe9da464dc613a
   1:     0x56480bbcd5eb - core::fmt::write::h31992ea73d92ffa4
   2:     0x56480bb9aecf - std::io::Write::write_fmt::h5015b998fbd1cf65
   3:     0x56480bb9e6de - std::sys::backtrace::print::h5f3f79d7ee85f598
   4:     0x56480bb9fc29 - std::panicking::default_hook::{{closure}}::hf313047c6f9a0750
   5:     0x56480bb9f9cc - std::panicking::default_hook::hd96acc715f65b6d7
   6:     0x56480bba0201 - std::panicking::rust_panic_with_hook::hc3b55609717126a2
   7:     0x56480bba0033 - std::panicking::begin_panic_handler::{{closure}}::h6a0db00056d37e77
   8:     0x56480bb9edc9 - std::sys::backtrace::__rust_end_short_backtrace::h8bf20a85e9b83f5c
   9:     0x56480bb9fd44 - rust_begin_unwind
  10:     0x56480bbca565 - core::panicking::panic_nounwind_fmt::hc22db378155c4432
  11:     0x56480bbca5f2 - core::panicking::panic_nounwind::he931df6ed8de2736
  12:     0x56480bbca736 - core::panicking::panic_cannot_unwind::h46449aa9b12c6d31
  13:     0x564809ccaf04 - <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline::hbe8669dd5c700595
  14:     0x7f45e2ccf32f - g_closure_invoke
  15:     0x7f45e2ce52bb - <unknown>
  16:     0x7f45e2ce7f83 - <unknown>
  17:     0x7f45e2cf13f9 - g_signal_emit_valist
  18:     0x7f45e2cf14c3 - g_signal_emit
  19:     0x7f45e200cee8 - <unknown>
  20:     0x7f45e200d066 - g_application_run
  21:     0x564809b93ec8 - <O as gio::application::ApplicationExtManual>::run_with_args::hf3ae39b800c31d15
  22:     0x564809c3b0e7 - celeste::main::h478561235040638f
  23:     0x564809d6ea63 - std::sys::backtrace::__rust_begin_short_backtrace::h4e646722653f7fdc
  24:     0x564809c6ec79 - std::rt::lang_start::{{closure}}::hb1f9c1b6a30502c1
  25:     0x56480bb92782 - std::rt::lang_start_internal::h55c3af6c910a5833
  26:     0x564809c3e205 - main
  27:     0x7f45e1a9ed90 - <unknown>
  28:     0x7f45e1a9ee40 - __libc_start_main
  29:     0x564809b55025 - _start
  30:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
```

### Installation Source

Snap

### What version of Celeste are you using?

unkown. The about screen shows "Unexpected element 'description' line: 2, symbol: 1"

### Storage Provider

Google Drive

**Comment by brenjn** [comment]
I have the same problem connecting to Proton Drive.
OS: KDE Neon

thread 'main' panicked at src/launch.rs:2040:33:
internal error: entered unreachable code
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: celeste::launch::launch::sync_local_directory
   4: celeste::launch::launch
   5: <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline
   6: g_closure_invoke
   7: <unknown>
   8: <unknown>
   9: g_signal_emit_valist
  10: g_signal_emit
  11: <unknown>
  12: g_application_run
  13: <O as gio::application::ApplicationExtManual>::run_with_args
  14: celeste::main
thread 'main' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x624b814e0905 - <std::sys::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hd7fe9da464dc613a
   1:     0x624b8150f5eb - core::fmt::write::h31992ea73d92ffa4
   2:     0x624b814dcecf - std::io::Write::write_fmt::h5015b998fbd1cf65
   3:     0x624b814e06de - std::sys::backtrace::print::h5f3f79d7ee85f598
   4:     0x624b814e1c29 - std::panicking::default_hook::{{closure}}::hf313047c6f9a0750
   5:     0x624b814e19cc - std::panicking::default_hook::hd96acc715f65b6d7
   6:     0x624b814e2201 - std::panicking::rust_panic_with_hook::hc3b55609717126a2
   7:     0x624b814e2033 - std::panicking::begin_panic_handler::{{closure}}::h6a0db00056d37e77
   8:     0x624b814e0dc9 - std::sys::backtrace::__rust_end_short_backtrace::h8bf20a85e9b83f5c
   9:     0x624b814e1d44 - rust_begin_unwind
  10:     0x624b8150c565 - core::panicking::panic_nounwind_fmt::hc22db378155c4432
  11:     0x624b8150c5f2 - core::panicking::panic_nounwind::he931df6ed8de2736
  12:     0x624b8150c736 - core::panicking::panic_cannot_unwind::h46449aa9b12c6d31
  13:     0x624b7f60cf04 - <O as gio::auto::application::ApplicationExt>::connect_activate::activate_trampoline::hbe8669dd5c700595
  14:     0x74a7b474b32f - g_closure_invoke
  15:     0x74a7b47612bb - <unknown>
  16:     0x74a7b4763f83 - <unknown>
  17:     0x74a7b476d3f9 - g_signal_emit_valist
  18:     0x74a7b476d4c3 - g_signal_emit
  19:     0x74a7b3a88ee8 - <unknown>
  20:     0x74a7b3a89066 - g_application_run
  21:     0x624b7f4d5ec8 - <O as gio::application::ApplicationExtManual>::run_with_args::hf3ae39b800c31d15
  22:     0x624b7f57d0e7 - celeste::main::h478561235040638f
  23:     0x624b7f6b0a63 - std::sys::backtrace::__rust_begin_short_backtrace::h4e646722653f7fdc
  24:     0x624b7f5b0c79 - std::rt::lang_start::{{closure}}::hb1f9c1b6a30502c1
  25:     0x624b814d4782 - std::rt::lang_start_internal::h55c3af6c910a5833
  26:     0x624b7f580205 - main
  27:     0x74a7b3518d90 - <unknown>
  28:     0x74a7b3518e40 - __libc_start_main
  29:     0x624b7f497025 - _start
  30:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.

**Comment by carlos-bitencourt** [comment]
Estava ocorrendo um problema semelhante, no meu caso, eu descobri que estava relacionado ao nome da pasta que estava com um espaço a mais no final. Eu percebi que o "crash" se dava ao tentar sincronizar determinada pasta e estava duplicando a pasta e parando. A duplicada tinha um caracter estranho no final. Excluí a pasta local e editei o nome diretamente no google drive online, e tentei a sincronia de novo daí passou.

**Comment by linuxwiz** [comment]
I am seeing the same error message on Linux Mint 22.1 with celeste 0.8.3

**Comment by spiegelsan** [comment]
Hello I have the same issue Mint 2.1 celeste 0.8.3

**Comment by packet-gal** [comment]
I have the same issue with Mint 22.1 and Celeste 0.8.3
