### ISSUE TITLE
[Bug]: Ubuntu 24.04 synchronisation fails with error

### ISSUE THREAD

**Issue by ouboub** [hwittenborn/celeste#227]
### Bug Description

The error occurs with the snap version and the one obtained from 
[prebuild](https://proget.makedeb.org prebuilt-mpr)
error is
```
thread 'main' panicked at src/launch.rs:2489:33:
internal error: entered unreachable code
stack backtrace:
thread 'main' panicked at library/core/src/panicking.rs:221:5:
panic in a function that cannot unwind
stack backtrace:
   0:     0x569c19592ed5 - <unknown>
   1:     0x569c195c1bbb - <unknown>
   2:     0x569c1958f49f - <unknown>
   3:     0x569c19592cae - <unknown>
   4:     0x569c195941f9 - <unknown>
   5:     0x569c19593f9c - <unknown>
   6:     0x569c195947d1 - <unknown>
   7:     0x569c19594603 - <unknown>
   8:     0x569c19593399 - <unknown>
   9:     0x569c19594314 - <unknown>
  10:     0x569c195beb35 - <unknown>
  11:     0x569c195bebc2 - <unknown>
  12:     0x569c195bed06 - <unknown>
  13:     0x569c176b23c4 - <unknown>
  14:     0x7cb49ed812fa - g_closure_invoke
  15:     0x7cb49edb090c - <unknown>
  16:     0x7cb49eda1591 - <unknown>
  17:     0x7cb49eda17c1 - g_signal_emit_valist
  18:     0x7cb49eda1883 - g_signal_emit
  19:     0x7cb49dd17690 - <unknown>
  20:     0x7cb49dd17823 - g_application_run
  21:     0x569c1757b388 - <unknown>
  22:     0x569c176225a7 - <unknown>
  23:     0x569c17755f23 - <unknown>
  24:     0x569c17656139 - <unknown>
  25:     0x569c19586d52 - <unknown>
  26:     0x569c176256c5 - <unknown>
  27:     0x7cb49d62a1ca - __libc_start_call_main
                               at ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
  28:     0x7cb49d62a28b - __libc_start_main_impl
                               at ./csu/../csu/libc-start.c:360:3
  29:     0x569c1753c4e5 - <unknown>
  30:                0x0 - <unknown>
thread caused non-unwinding panic. aborting.
```

### Installation Source

Snap

### What version of Celeste are you using?

0.83-1

### Storage Provider

Google Drive

**Comment by ShadowDrakken** [comment]
Same on 0.8.3 flatpak

**Comment by mathiasdg** [comment]
i have the same problem, trying to sync Dropbox on 0.8.3 flatpak

**Comment by darvo90** [comment]
same on 0.8.3 flatpak

**Comment by bukbr** [comment]
same here 0.8.3 flatpak

**Comment by hh44bbbbyy** [comment]
Had the same issue on the most recent flatpak release (0.8.3). It happend when a new file was added to the local directory and Celeste was already running but could not sync before. as the Wi-Fi connection was disabled from startup on. Plain WebDAV connection.
