### ISSUE TITLE
Crash and error message after trying to delete folder connection

### ISSUE THREAD

**Issue by pflanzenandi** [hwittenborn/celeste#41]
`thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', celeste/src/launch.rs:416:134
stack backtrace:`

When trying to restart the app, only the error message gets shown. When exiting the message, app process gets closed too. UI never starts.

Pop_OS 22.04
Nextcloud
Flatpak

**Comment by hwittenborn** [comment]
Thanks for reporting the issue! I suspect this might be a regression from a recent commit (I'm thinking it's probably https://github.com/hwittenborn/celeste/commit/b87b8a0d76bb264b1c55f1c621ac06010d3eb840), but I'll do some more testing once I get home. I'll send a message once I have more info.

**Comment by tazihad** [comment]
I am also facing similar issue.
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Exec(SqlxError(Database(SqliteError { code: 787, message: "FOREIGN KEY constraint failed" })))', celeste/src/launch.rs:2281:26
```
