### ISSUE TITLE
Unknown error - thread 'main' panicked.

### ISSUE THREAD

**Issue by tazihad** [hwittenborn/celeste#49]
Everytime I try to sync Google Drive. I get the same error. 
```
thread 'main' panicked at 'internal error: entered unreachable code', celeste/src/launch.rs:2226:33
stack backtrace:
```
And the app crash.

**Comment by hwittenborn** [comment]
@tazihad: Can you confirm if the issue is still happening? I haven't been able to find out what triggers the issue yet, and I likewise haven't been able to reproduce it again yet either.

**Comment by tazihad** [comment]
@hwittenborn I just checked. I get similar error. I have around 1 gb file on google drive. App crash after few minutes during sync. Not sure why.
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Exec(SqlxError(Database(SqliteError { code: 787, message: "FOREIGN KEY constraint failed" })))', celeste/src/launch.rs:2281:26
```

I am using Fedora Kinoite 37.
celeste from flathub.

**Comment by nboughton** [comment]
Same issue but no stack trace appears in the error window

![image](https://user-images.githubusercontent.com/8879583/221328991-c9423af3-389c-4da8-b24d-e2c6ca4e57e5.png)

**Comment by hwittenborn** [comment]
I'm waiting for the Flatpak to deploy, and then I'm going to give this another look. I'm thinking it might've been fixed since the latest Flatpak release, but I'm not positive yet. The new Flatpak should be out in ~2 hours, but I'll send a message here once it's out.

**Comment by hwittenborn** [comment]
The Flatpak should be updated now, could you see if the issue persists @tazihad @nboughton?

**Comment by gonzoknows** [comment]
Getting the same error
![image](https://user-images.githubusercontent.com/122128828/221344145-9309ab09-f8a0-47f3-9cac-b6acb506102e.png)

**Comment by tazihad** [comment]
@hwittenborn Tried the latest version. Issue still exist.

**Comment by nboughton** [comment]
Same issue still occurring for me too. I also noted that one of my cpu cores is permanently at 100% whenever Celeste is running.

**Comment by gonzoknows** [comment]
> 

That's a good find, I'm getting the same issues on my CPU core 15
![image](https://user-images.githubusercontent.com/122128828/221382395-beda6f76-b35c-4fac-87fd-0d0093d59874.png)

**Comment by hwittenborn** [comment]
Hmm - it looks like this is only happening for the Google Drive backend - do you guys use any other backends? If not then I'm pretty sure this is related to Google Drive somehow.

**Comment by tazihad** [comment]
@hwittenborn You are right. I only use Google Drive. Not sure about other cloud service.

**Comment by nboughton** [comment]
I also only use Google Drive so I can't comment on the other services.

**Comment by gonzoknows** [comment]
> Hmm - it looks like this is only happening for the Google Drive backend - do you guys use any other backends? If not then I'm pretty sure this is related to Google Drive somehow.

I only use Google Drive too, as I get unlimited storage from my institution

**Comment by hwittenborn** [comment]
Yeah, this is definitely just an issue with Google Drive, I've tried to make other remotes break but I don't recall ever getting anything. I'll see if Google Drive is reporting some kind of information Celeste isn't expecting and send a message once I do some testing.

**Comment by gonzoknows** [comment]
> Yeah, this is definitely just an issue with Google Drive, I've tried to make other remotes break but I don't recall ever getting anything. I'll see if Google Drive is reporting some kind of information Celeste isn't expecting and send a message once I do some testing.

Definitely thanks for being quick to address this issue. Cloud support for my pc is very useful especially for school.

**Comment by hwittenborn** [comment]
> I'll also add releases before v0.4.6 worked fine with syncing, it was just slow

Thanks for the info - I'm still trying to figure out why this is going on, but I'll see if I can find anything that changed in the past few releases that might be causing something.

**Comment by gonzoknows** [comment]
> > I'll also add releases before v0.4.6 worked fine with syncing, it was just slow
> 
> Thanks for the info - I'm still trying to figure out why this is going on, but I'll see if I can find anything that changed in the past few releases that might be causing something.

I tried downgrading the flatpak, but it gives an error about the database

**Comment by hwittenborn** [comment]
Celeste doesn't currently support downgrading to an earlier version after you update (at least most of the time, whenever the database layout gets updated then you can't go backward).

If you want to go back to an earlier release you'll need to delete `rclone.conf` and `celeste.db` in `~/.var/app/com.hunterwittenborn.Celeste/config`, and then sign back in to your remotes. You can also do some stuff manually to get it working, but it'd be easiest to just redo everything from scratch.

**Comment by gonzoknows** [comment]
> Celeste doesn't currently support downgrading to an earlier version after you update (at least most of the time, whenever the database layout gets updated then you can't go backward).
> 
> If you want to go back to an earlier release you'll need to delete `rclone.conf` and `celeste.db` in `~/.var/app/com.hunterwittenborn.Celeste/config`, and then sign back in to your remotes. You can also do some stuff manually to get it working, but it'd be easiest to just redo everything from scratch.

Oh okay haha, I'll just wait for this issue to be resolved

**Comment by gonzoknows** [comment]
This error seems to be persistent even without Wi-Fi or an active Internet. I just wanted to add that.

**Comment by hwittenborn** [comment]
Yeah that makes sense @gonzoknows, it's checking previously recorded hashes when that error occurs iirc, so it makes sense that it'd happen like that

**Comment by gonzoknows** [comment]
> Yeah that makes sense @gonzoknows, it's checking previously recorded hashes when that error occurs iirc, so it makes sense that it'd happen like that

Any updates on the status on this Error

**Comment by gonzoknows** [comment]
> Yeah that makes sense @gonzoknows, it's checking previously recorded hashes when that error occurs iirc, so it makes sense that it'd happen like that

New update: I've noticed the thread only panics when there are no more items to sync to google drive. 

My example is when I was backing up a Cryptomator vault to google cloud, once it syncs all the files the thread panics then the app basically spits the error and breaks.

**Comment by gonzoknows** [comment]
Thread panicked in latest release 
![image](https://user-images.githubusercontent.com/122128828/228250359-716be8e2-c65d-4cb9-8acb-c09a082c6706.png)
